/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.tl330.battleship;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;

public class App {
  private TextPlayer player1;
  private TextPlayer player2;

  // constructor
  public App(TextPlayer player1, TextPlayer player2) {
    this.player1 = player1;
    this.player2 = player2;

  }

  public void doPlacementPhase() throws IOException {
    this.player1.doPlacementPhase();
    this.player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException {
    while (true) {
      if (player1.theBoard.noShips()) {
        player1.out.println("Player " + player2.name + " win. Player " + player1.name + " lose.");
        return;
      }
      player1.doOneAction(player2);
      if (player2.theBoard.noShips()) {
        player2.out.println("Player " + player1.name + " win. Player " + player2.name + " lose.");
        return;
      }
      player2.doOneAction(player1);
    }

  }

  static String getAllPlacement() {
    String ans = "";
    String fire = "F\n";
    for (char c = 'A'; c < 'U'; c++) {
      for (int i = 0; i < 10; i++) {
        ans = ans + fire + c + i + "\n";
      }
    }
    return ans;
  }

  static TextPlayer makePlayer(String name, Board<Character> b, BufferedReader input, PrintStream out,
      V1ShipFactory factory)
      throws IOException {
    BufferedReader input_computer = new BufferedReader(new StringReader("a0h\na2h\na4h\na7h\nb0h\nb3d\nb6d\nc0d\nC3U\nc5u\n" + getAllPlacement()));
    out.println("Is player "+name+" computer? (Y for yes, N for no)");
    String s1 = input.readLine();
    // toUpperCase
    while (!(s1.equals("Y") || s1.equals("N"))) {
      out.println("Input needs to be Y or N.");
      s1 = input.readLine();
    }
    if (s1.equals("Y")) {
      return new TextPlayer(name, b, input_computer, out, factory, false);
    } else {
      return new TextPlayer(name, b, input, out, factory);
    }
  }

  public static void main(String[] args) throws IOException {

    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    BufferedReader input1 = new BufferedReader(new StringReader("" + getAllPlacement()));
    BufferedReader input2 = new BufferedReader(new StringReader("" + getAllPlacement()));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer p1 = makePlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = makePlayer("B", b2, input, System.out, factory);

    App app = new App(p1, p2);
    app.doPlacementPhase();
    app.doAttackingPhase();
  }
}
