/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.tl330.battleship;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;

public class App {

  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;// System.out;
  }

  public Placement readPlacement(String prompt) throws IOException {
    // out.println(prompt);
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {
    Placement p = readPlacement("Where would you like to put your ship?");
    RectangleShip<Character> s = new RectangleShip<Character>(p.getWhere(), 's', '*');
    theBoard.tryAddShip(s);
    out.println(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException{
    Board<Character> b = new BattleShipBoard<Character>(10, 20);
    App a=new App(b,new InputStreamReader(System.in),System.out);
    a.doOnePlacement();
    
  }
}
